# Docker Compose file for Gremlins on docker

# Build with:
# docker-compose build gremlins-on-docker

# Run with:
# docker-compose up

services:
    gremlins-on-docker:
        platform: "linux/amd64"
        build: .
        container_name: playwright
        privileged: true
        shm_size: '512mb'
        restart: unless-stopped
        volumes:
            - "./playwright/:/playwright/project/"

# Uncomment bellow If logs will be sent to elasticsearch via TCP
#networks:
#    default:
#        name: docker-elk_elk
#        external: true